# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.v2.jsonschema.json
version: "2"
linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - nakedret
    - prealloc
    - unparam
    - misspell
    - gocritic
    - dupl
    - gocyclo
    - funlen
    - bodyclose
    - durationcheck
    - errorlint
    - forcetypeassert
    - goheader
    - gomodguard
    - makezero
    - nilerr
    - noctx
    - perfsprint
    - reassign
    - testpackage
    - tparallel
    - wastedassign
formatters:
  enable:
    - gofumpt
    - goimports
linters-settings:
  funlen:
    lines: 200
    statements: 100
issues:
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - funlen
