---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sakuracloud-secrets
  namespace: default
spec:
  provider: sakuracloud
  parameters:
    vaultID: "your-vault-id"  # Replace with your Sakura Cloud Secret Manager Vault ID
    secrets: |
      - name: "my-secret-1"
      - name: "my-secret-2"