apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

metadata:
  name: secrets-store-csi-driver-provider-sakuracloud

resources:
  - rbac.yaml
  - daemonset.yaml

labels:
  - pairs:
      app.kubernetes.io/name: secrets-store-csi-driver-provider-sakuracloud
      app.kubernetes.io/component: provider

images:
  - name: ghcr.io/tosuke/secrets-store-csi-driver-provider-sakuracloud
    newTag: v0.2.1
