---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver-provider-sakuracloud
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-store-csi-driver-provider-sakuracloud
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-store-csi-driver-provider-sakuracloud
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-store-csi-driver-provider-sakuracloud
subjects:
  - kind: ServiceAccount
    name: secrets-store-csi-driver-provider-sakuracloud