apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: default
  name: basic-test
spec:
  provider: sakuracloud
  parameters:
    vaultID: "${SAKURACLOUD_VAULT_ID}"
    secrets: |
      - name: test1
