name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: failure()
    permissions: {}
    steps: [{ run: exit 1 }]
    needs:
      - go-test
      - go-lint
      - build-image

  go-test:
    name: Go Test
    uses: ./.github/workflows/wf-go-test.yaml
    with:
      save-cache: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

  go-lint:
    name: Go Lint
    uses: ./.github/workflows/wf-go-lint.yaml
    with:
      save-cache: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

  build-image:
    name: Build Docker Image
    uses: ./.github/workflows/wf-build-and-push-docker-image.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: ${{ github.repository }}
      push: false
