name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      e2e: ${{ steps.changes.outputs.e2e }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            e2e:
              - .github/workflows/wf-e2e-test.yaml
              - '**/*.go'
              - go.mod
              - go.sum
              - 'e2e/**'
              - Dockerfile
              - aqua.yaml

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: failure()
    permissions: {}
    needs: [changes, go-test, go-lint, build-image, e2e-test]
    steps: [{ run: exit 1 }]

  go-test:
    name: Go Test
    uses: ./.github/workflows/wf-go-test.yaml
    with:
      save-cache: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

  go-lint:
    name: Go Lint
    uses: ./.github/workflows/wf-go-lint.yaml
    with:
      save-cache: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

  build-image:
    name: Build Docker Image
    uses: ./.github/workflows/wf-build-and-push-docker-image.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      image_name: ${{ github.repository }}
      push: false
      save-cache: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

  e2e-test:
    name: E2E Test
    needs: changes
    if: needs.changes.outputs.e2e == 'true'
    uses: ./.github/workflows/wf-e2e-test.yaml
    with:
      is-pr: ${{ github.event_name == 'pull_request' }}
    secrets: inherit
