name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true
      - uses: Songmu/tagpr@ebb5da0cccdb47c533d4b520ebc0acd475b16614 # v1.7.0
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docker-image:
    needs: [tagpr]
    if: ${{ needs.tagpr.outputs.tag != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/wf-build-and-push-docker-image.yaml
    with:
      image_name: ${{ github.repository }}
      push: true
      version: ${{ needs.tagpr.outputs.tag }}
      save-cache: true

  release-deploy-yaml:
    needs: [tagpr]
    if: ${{ needs.tagpr.outputs.tag != '' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.5
      - name: Build deploy.yaml
        run: |
          kubectl kustomize -o deploy.yaml ./deploy
      - name: Upload deploy.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload \
            --clobber \
            --repo ${{ github.repository }} \
            ${{ needs.tagpr.outputs.tag }} \
            deploy.yaml
