name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: true
      - uses: Songmu/tagpr@7191605433b03e11b313dbbc0efb80185170de4b # v1.9.0
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docker-image:
    needs: [tagpr]
    if: ${{ needs.tagpr.outputs.tag != '' }}
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/wf-build-and-push-docker-image.yaml
    with:
      image_name: ${{ github.repository }}
      push: true
      version: ${{ needs.tagpr.outputs.tag }}
      save-cache: true

  release-deploy-yaml:
    needs: [tagpr]
    if: ${{ needs.tagpr.outputs.tag != '' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.55.0
      - name: Build deploy.yaml
        run: |
          kubectl kustomize -o deploy.yaml ./deploy
      - name: Upload deploy.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload \
            --clobber \
            --repo ${{ github.repository }} \
            ${{ needs.tagpr.outputs.tag }} \
            deploy.yaml
