name: E2E Test

on:
  workflow_call:
    inputs:
      is-pr:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version: ${{ fromJSON(inputs.is-pr && '["v1.33.1"]' || '["v1.31.6", "v1.32.3", "v1.33.1"]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
          cache: false

      - name: Install Aqua
        uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.64.0

      - name: Create kind cluster
        run: |
          kind create cluster --config e2e/kind.yaml --wait 300s --image "kindest/node:$K8S_VERSION"
        env:
          K8S_VERSION: ${{ matrix.k8s-version }}

      - name: Run E2E tests
        run: |
          make e2e-test

      - name: Cleanup kind cluster
        if: always()
        run: |
          kind delete cluster || true
