name: E2E Test

on:
  workflow_call:
    secrets:
      SAKURACLOUD_ACCESS_TOKEN:
        required: true
      SAKURACLOUD_ACCESS_TOKEN_SECRET:
        required: true
      SAKURACLOUD_TEST_VAULT_ID:
        required: true

permissions:
  contents: read

jobs:
  unseal-secrets:
    runs-on: ubuntu-latest
    environment:
      name: sacloud
      url: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
    outputs:
      sakuracloud-access-token: ${{ steps.export-secrets.outputs.sakuracloud-access-token }}
      sakuracloud-access-token-secret: ${{ steps.export-secrets.outputs.sakuracloud-access-token-secret }}
      sakuracloud-test-vault-id: ${{ steps.export-secrets.outputs.sakuracloud-test-vault-id }}
    steps:
      - name: Export secrets
        id: export-secrets
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN_SECRET }}
          SAKURACLOUD_TEST_VAULT_ID: ${{ secrets.SAKURACLOUD_TEST_VAULT_ID }}
        run: |
          echo "::add-mask::${SAKURACLOUD_ACCESS_TOKEN}"
          echo "::add-mask::${SAKURACLOUD_ACCESS_TOKEN_SECRET}"
          echo "::add-mask::${SAKURACLOUD_TEST_VAULT_ID}"
          echo "sakuracloud-access-token=${SAKURACLOUD_ACCESS_TOKEN}" >> "$GITHUB_OUTPUT"
          echo "sakuracloud-access-token-secret=${SAKURACLOUD_ACCESS_TOKEN_SECRET}" >> "$GITHUB_OUTPUT"
          echo "sakuracloud-test-vault-id=${SAKURACLOUD_TEST_VAULT_ID}" >> "$GITHUB_OUTPUT"

  e2e-test:
    runs-on: ubuntu-latest
    needs: [unseal-secrets]
    concurrency:
      group: e2e-test
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        k8s-version:
          - v1.31.6
          - v1.32.3
          - v1.33.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: stable
          cache: false

      - name: Install Aqua
        uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.4

      - name: Create kind cluster
        run: |
          kind create cluster --wait 300s --image "kindest/node:$K8S_VERSION"
        env:
          K8S_VERSION: ${{ matrix.k8s-version }}

      - name: Run E2E tests
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ needs.unseal-secrets.outputs.sakuracloud-access-token }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ needs.unseal-secrets.outputs.sakuracloud-access-token-secret }}
          SAKURACLOUD_VAULT_ID: ${{ needs.unseal-secrets.outputs.sakuracloud-test-vault-id }}
        run: |
          make e2e-test

      - name: Cleanup kind cluster
        if: always()
        run: |
          kind delete cluster || true
