name: E2E Test

on:
  workflow_call:
    secrets:
      SAKURACLOUD_ACCESS_TOKEN:
        required: true
      SAKURACLOUD_ACCESS_TOKEN_SECRET:
        required: true
      SAKURACLOUD_TEST_VAULT_ID:
        required: true
      E2E_SECRET_KEY:
        required: true

permissions:
  contents: read

jobs:
  unseal-secrets:
    runs-on: ubuntu-latest
    environment:
      name: sacloud
      url: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
    outputs:
      sakuracloud-access-token: ${{ steps.encrypt-secrets.outputs.sakuracloud-access-token }}
      sakuracloud-access-token-secret: ${{ steps.encrypt-secrets.outputs.sakuracloud-access-token-secret }}
      sakuracloud-test-vault-id: ${{ steps.encrypt-secrets.outputs.sakuracloud-test-vault-id }}
    steps:
      - name: Encrypt secrets
        id: encrypt-secrets
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN_SECRET }}
          SAKURACLOUD_TEST_VAULT_ID: ${{ secrets.SAKURACLOUD_TEST_VAULT_ID }}
          KEY: ${{ secrets.E2E_SECRET_KEY }}
        run: |
          ENCRYPTED_TOKEN=$(echo -n "$SAKURACLOUD_ACCESS_TOKEN" | openssl enc -e -aes-256-cbc -pbkdf2 -salt -a -A -k "$KEY")
          ENCRYPTED_TOKEN_SECRET=$(echo -n "$SAKURACLOUD_ACCESS_TOKEN_SECRET" | openssl enc -e -aes-256-cbc -pbkdf2 -salt -a -A -k "$KEY")
          ENCRYPTED_VAULT_ID=$(echo -n "$SAKURACLOUD_TEST_VAULT_ID" | openssl enc -e -aes-256-cbc -pbkdf2 -salt -a -A -k "$KEY")
          {
            echo "sakuracloud-access-token=$ENCRYPTED_TOKEN"
            echo "sakuracloud-access-token-secret=$ENCRYPTED_TOKEN_SECRET"
            echo "sakuracloud-test-vault-id=$ENCRYPTED_VAULT_ID"
          } >> "$GITHUB_OUTPUT"

  e2e-test:
    runs-on: ubuntu-latest
    needs: [unseal-secrets]
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - v1.31.6
          - v1.32.3
          - v1.33.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
          cache: false

      - name: Install Aqua
        uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.5

      - name: Decrypt secrets
        id: decrypt-secrets
        env:
          KEY: ${{ secrets.E2E_SECRET_KEY }}
          ENCRYPTED_TOKEN: ${{ needs.unseal-secrets.outputs.sakuracloud-access-token }}
          ENCRYPTED_TOKEN_SECRET: ${{ needs.unseal-secrets.outputs.sakuracloud-access-token-secret }}
          ENCRYPTED_VAULT_ID: ${{ needs.unseal-secrets.outputs.sakuracloud-test-vault-id }}
        run: |
          SAKURACLOUD_ACCESS_TOKEN=$(echo -n "$ENCRYPTED_TOKEN" | openssl enc -d -aes-256-cbc -pbkdf2 -salt -a -A -k "$KEY")
          SAKURACLOUD_ACCESS_TOKEN_SECRET=$(echo -n "$ENCRYPTED_TOKEN_SECRET" | openssl enc -d -aes-256-cbc -pbkdf2 -salt -a -A -k "$KEY")
          SAKURACLOUD_VAULT_ID=$(echo -n "$ENCRYPTED_VAULT_ID" | openssl enc -d -aes-256-cbc -pbkdf2 -salt -a -A -k "$KEY")
          {
            echo "sakuracloud-access-token=$SAKURACLOUD_ACCESS_TOKEN"
            echo "sakuracloud-access-token-secret=$SAKURACLOUD_ACCESS_TOKEN_SECRET"
            echo "sakuracloud-vault-id=$SAKURACLOUD_VAULT_ID"
          } >> "$GITHUB_OUTPUT"
          echo "::add-mask::$SAKURACLOUD_ACCESS_TOKEN"
          echo "::add-mask::$SAKURACLOUD_ACCESS_TOKEN_SECRET"
          echo "::add-mask::$SAKURACLOUD_VAULT_ID"

      - name: Create kind cluster
        run: |
          kind create cluster --wait 300s --image "kindest/node:$K8S_VERSION"
        env:
          K8S_VERSION: ${{ matrix.k8s-version }}

      - name: Run E2E tests
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ steps.decrypt-secrets.outputs.sakuracloud-access-token }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ steps.decrypt-secrets.outputs.sakuracloud-access-token-secret }}
          SAKURACLOUD_VAULT_ID: ${{ steps.decrypt-secrets.outputs.sakuracloud-vault-id }}
        run: |
          make e2e-test

      - name: Cleanup kind cluster
        if: always()
        run: |
          kind delete cluster || true
