name: E2E Test

on:
  workflow_call:
    inputs:
      is-pr:
        required: true
        type: boolean
    secrets:
      SAKURACLOUD_ACCESS_TOKEN:
        required: true
      SAKURACLOUD_ACCESS_TOKEN_SECRET:
        required: true
      SAKURACLOUD_TEST_VAULT_ID:
        required: true

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.is-pr && 'sacloud-pr' || 'sacloud' }}
      url: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
    strategy:
      fail-fast: false
      matrix:
        k8s-version: ${{ fromJSON(inputs.is-pr && '["v1.33.1"]' || '["v1.31.6", "v1.32.3", "v1.33.1"]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: stable
          cache: false

      - name: Install Aqua
        uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.53.9

      - name: Create kind cluster
        run: |
          kind create cluster --wait 300s --image "kindest/node:$K8S_VERSION"
        env:
          K8S_VERSION: ${{ matrix.k8s-version }}

      - name: Run E2E tests
        env:
          SAKURACLOUD_ACCESS_TOKEN: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN }}
          SAKURACLOUD_ACCESS_TOKEN_SECRET: ${{ secrets.SAKURACLOUD_ACCESS_TOKEN_SECRET }}
          SAKURACLOUD_VAULT_ID: ${{ secrets.SAKURACLOUD_TEST_VAULT_ID }}
        run: |
          make e2e-test

      - name: Cleanup kind cluster
        if: always()
        run: |
          kind delete cluster || true
