name: Go Lint

on:
  workflow_call:
    inputs:
      save-cache:
        required: false
        type: boolean
        default: false

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Aqua
        uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.64.0
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          install-mode: none
          skip-save-cache: ${{ inputs.save-cache != 'true' }}

  license-check:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=go depName=github.com/google/go-licenses
      GOLICENSES_VERSION: 1.6.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
          cache: false
      - name: Install go-licenses
        run: go install github.com/google/go-licenses@v${{ env.GOLICENSES_VERSION }}
      - name: Check license compliance
        run: go-licenses check ./...
