---
name: yamlfmt
on:
  push:
  pull_request:
jobs:
  yamlfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aquaproj/aqua-installer@v3.2.1
      with:
        aqua_version: v2.42.3
    - run: yamlfmt -d .