name: yamlfmt
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  yamlfmt:
    name: YAML Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Aqua
        uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.5
      - name: Check YAML formatting
        run: |-
          if ! yamlfmt -dry .; then
            echo "YAML files are not formatted correctly. Please run 'yamlfmt .' to fix them."
            exit 1
          fi
